-   id: msg-rules-enforcement
    name: Message format enforcement
    description: Verifies that commit message contains reference to task tracker and conventional versions prefix
    entry: msg-rules-enforcement
    language: python
    always_run: true
    stages: [prepare-commit-msg]
